# Generated by Django 5.1.6 on 2026-02-22 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proctoring", "0014_alter_cheatingaudio_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="student_answers",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="cheatingaudio",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 2, 23, 1, 14, 29, 461325)
            ),
        ),
        migrations.AlterField(
            model_name="cheatingevent",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 2, 23, 1, 14, 29, 461325)
            ),
        ),
        migrations.AlterField(
            model_name="cheatingimage",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 2, 23, 1, 14, 29, 461325)
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 2, 23, 1, 14, 29, 461325)
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 2, 23, 1, 14, 29, 461325)
            ),
        ),
    ]
